### ISSUE TITLE
feature - Implementation of the header component

### ISSUE THREAD

**Issue by emanuelamarkovic** [emanuelamarkovic/dev-portfolio#1]
### Task
Implement the `Header` component for the navigation of the website.

### Requirements

- [x]  the navigation should contain links to the following areas:

   - Home
   - About
   - Skills
   - Portfolio
   - Contact

- [x] use semantic HTML (e.g. `<header>` and `<nav>`).

- [x] the links should be functional and lead to the relevant sections.
